# check task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: horizon-check
spec:
  params:
    - name: token
    - name: application
    - name: cluster
    - name: clusterID
    - name: environment
    - name: gitRepositoryUrl
    - name: gitSubfolder
    - name: gitCommit
    - name: gitBranch
    - name: gitTag
    - name: pipelineJSONBlob
    - name: imageURL
    - name: pipelinerunID
    - name: requestID
    - name: template
    - name: action
  steps:
    - name: check
      image: {{ .Values.horizon.checkTask.image.checkStep }}
      {{- with .Values.horizon.checkTask.timeout.checkStep }}
      timeout: {{.}}
      {{- end}}
      script:
      {{ toYaml (tpl .Values.horizon.script.check .) | nindent 8 }}
      {{ if .Values.extraVolumeMounts -}}
      volumeMounts:
{{- include "tektonci.extraVolumeMounts" . | indent 8 }}
      {{- end }}
  {{ if .Values.extraVolumeMounts -}}
  volumes:
{{- include "tektonci.extraVolumes" . | indent 4 }}
  {{- end }}
