# default pipeline
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: horizon-pipeline
spec:
  params:
    - name: token
      type: string
    - name: application
      type: string
    - name: cluster
      type: string
    - name: clusterID
      type: string
    - name: environment
      type: string
    - name: gitRepositoryUrl
      type: string
    - name: gitSubfolder
      type: string
    - name: gitCommit
      type: string
    - name: gitBranch
      type: string
    - name: gitTag
      type: string
    - name: pipelineJSONBlob
      type: string
    - name: imageURL
      type: string
    - name: pipelinerunID
      type: string
    - name: requestID
      type: string
    - name: template
      type: string
    - name: action
      type: string
  workspaces:
    - name: buildinfo
  tasks:
    - name: build
      taskRef:
        name: horizon-build
      when:
        - input: "$(params.action)"
          operator: in
          values: ["builddeploy"]
      params:
        - name: token
          value: $(params.token)
        - name: application
          value: $(params.application)
        - name: cluster
          value: $(params.cluster)
        - name: clusterID
          value: $(params.clusterID)
        - name: environment
          value: $(params.environment)
        - name: gitRepositoryUrl
          value: $(params.gitRepositoryUrl)
        - name: gitSubfolder
          value: $(params.gitSubfolder)
        - name: gitCommit
          value: $(params.gitCommit)
        - name: gitBranch
          value: $(params.gitBranch)
        - name: gitTag
          value: $(params.gitTag)
        - name: pipelineJSONBlob
          value: $(params.pipelineJSONBlob)
        - name: imageURL
          value: $(params.imageURL)
        - name: pipelinerunID
          value: $(params.pipelinerunID)
        - name: requestID
          value: $(params.requestID)
        - name: template
          value: $(params.template)
        - name: action
          value: $(params.action)
      workspaces:
        - name: buildinfo
          workspace: buildinfo
    - name: check
      taskRef:
        name: horizon-check
      runAfter:
        - build
      params:
        - name: token
          value: $(params.token)
        - name: application
          value: $(params.application)
        - name: cluster
          value: $(params.cluster)
        - name: clusterID
          value: $(params.clusterID)
        - name: environment
          value: $(params.environment)
        - name: gitRepositoryUrl
          value: $(params.gitRepositoryUrl)
        - name: gitSubfolder
          value: $(params.gitSubfolder)
        - name: gitCommit
          value: $(params.gitCommit)
        - name: gitBranch
          value: $(params.gitBranch)
        - name: gitTag
          value: $(params.gitTag)
        - name: pipelineJSONBlob
          value: $(params.pipelineJSONBlob)
        - name: imageURL
          value: $(params.imageURL)
        - name: pipelinerunID
          value: $(params.pipelinerunID)
        - name: requestID
          value: $(params.requestID)
        - name: template
          value: $(params.template)
        - name: action
          value: $(params.action)
    - name: deploy
      taskRef:
        name: horizon-deploy
      runAfter:
        - check
      params:
        - name: token
          value: $(params.token)
        - name: application
          value: $(params.application)
        - name: cluster
          value: $(params.cluster)
        - name: clusterID
          value: $(params.clusterID)
        - name: environment
          value: $(params.environment)
        - name: gitRepositoryUrl
          value: $(params.gitRepositoryUrl)
        - name: gitSubfolder
          value: $(params.gitSubfolder)
        - name: gitCommit
          value: $(params.gitCommit)
        - name: gitBranch
          value: $(params.gitBranch)
        - name: gitTag
          value: $(params.gitTag)
        - name: pipelineJSONBlob
          value: $(params.pipelineJSONBlob)
        - name: imageURL
          value: $(params.imageURL)
        - name: pipelinerunID
          value: $(params.pipelinerunID)
        - name: requestID
          value: $(params.requestID)
        - name: template
          value: $(params.template)
        - name: action
          value: $(params.action)
