# sa to run the pipeline, includes git-secret, git-token and harbor-secret
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
secrets:
  - name: git-secret
  - name: git-token
  - name: harbor-secret