{{ $hasPSP := .Capabilities.APIVersions.Has "policy/v1bata1/PodSecurityPolicy"}}
{{ if $hasPSP }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:tekton-resources
rules:
  - verbs:
      - use
    apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - tekton-resources
{{ end }}
